# Centos Pull
FROM centos

VOLUME /home/apache

# Take proxy env if it's configured in docker
#ENV http_proxy <HTTP_PROXY>
#ENV https_proxy <HTTPS_PROXY>

MAINTAINER derioss https://github.com/Derioss



# Update image
RUN useradd -u 1000 apache && \
    yum -y install epel-release && \
    yum install -y vim && \
    yum install -y yum-utils && \
    yum install -y httpd && \
    yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum-config-manager --enable remi-php72 && \
    yum install -y git && \
    yum install -y php && \
    yum install -y php-mcrypt.x86_64 && \
    yum install -y php-cli && \
    yum install -y php-gd && \
    yum install -y php-curl && \
    yum install -y php-mysql && \
    yum install -y php-ldap && \
    yum install -y php-xml && \
    yum install -y php-mbstring && \
    yum install -y php-zip && \
    yum install -y wget && \
    yum install -y net-tools && \
    yum install -y unzip && \
    yum clean all


# composer install
RUN curl -o /tmp/composer-setup.php https://getcomposer.org/installer \
&& curl -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
# Make sure we're installing what we think we're installing!
&& php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }" \
&& php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --snapshot \
&& rm -f /tmp/composer-setup.*


RUN systemctl enable httpd


WORKDIR /tmp/laravel
# install laravel
COPY laravel/ /tmp/laravel
RUN  composer install

COPY laravel.conf /etc/httpd/conf.d/

# Expose port
EXPOSE 80


# apache right



COPY ./docker-entrypoint.sh ../
RUN chmod  +x ../docker-entrypoint.sh && \
    chown -R apache: ../docker-entrypoint.sh && \
    chown -R apache: /tmp/laravel && \
    chmod 644 /etc/httpd/conf/httpd.conf

ENTRYPOINT ["/tmp/docker-entrypoint.sh"]
