version: '3.3'

services:
   db:
    container_name: db
    image: centos/mariadb-101-centos7
    volumes:
      - ./db_data:/var/lib/mysql/data    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret


   laravel:
    image: laravel_dev
    container_name: laravel
    ports:
      - "8080:80"
    volumes:
       - ./apache:/home/apache
    links:
      - db:database

    restart: always
